# Generated by Django 5.0.1 on 2024-01-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
    ]
