# Generated by Django 5.0.1 on 2024-01-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(verbose_name='дата оплаты'),
        ),
    ]
