# Generated by Django 5.0.1 on 2024-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_coursesubscription_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_summ',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='cтоимость курса'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сессия для оплаты'),
        ),
    ]
